name: Security Check on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Run security check
        run: |
          python check_vulnerabilities.py  # This is where you'll call your backend to check the code
