name: Security Check

on:
  pull_request:
    branches: [ main ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install fastapi uvicorn transformers torch requests
          # Install your backend dependencies for code_review.py
      - name: Run Vulnerability Check (Demo)
        run: |
          echo "Running demo vulnerability scan on backend/test.js"
          python sec_pull/backend/code_review.py --file sec_pull/backend/test.js > security_report.txt
          echo "--- SECURITY REPORT OUTPUT ---"
          cat security_report.txt
      - name: Upload Security Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security_report.txt